#!/usr/bin/env python
#created by Yifei.Fu at 2015-01-21


TESTCASE_ID="Tc.config.func.001"
TESTCASE_PRI= "H"

import os,sys,pexpect,time

if __name__ == '__main__':
    """Config module in each nodes can start up and run correctly in 5 minutes after the node start up."""

    #####################<prerequisites>########################
    #caller pass the workdir pathname,test conf by commandline args
    workdir = sys.argv[1]
    conf = eval(sys.argv[2])
    os.chdir(workdir)

    #load TestModules
    sys.path.append(conf["test_lib_dir"])
    from interact import *

    #prepare files for vpn dp
    prepare_file(conf,'vpn')
    prepare_file(conf,'dp')

    #login to vpn,dp
    ssh_vpn_proc = pexpect.spawn("ssh %s"%(conf['vpns']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc,'vpn')
    ssh_dp_proc = pexpect.spawn("ssh %s"%(conf['dps']['1st']['ssh']))
    wait_server(conf,ssh_dp_proc,'dp')
    #if ./TestBench/ not exist on vpn&dp,then create it
    ssh_vpn_proc.sendline("if [ ! -d 'TestBench'  ];then mkdir TestBench;fi;cd TestBench")
    wait_server(conf,ssh_vpn_proc,'vpn')
    ssh_dp_proc.sendline("if [ ! -d 'TestBench'  ];then mkdir TestBench;fi;cd TestBench")
    wait_server(conf,ssh_dp_proc,'dp')
    #transmit scripts to vpn,dp
    newbash_proc = pexpect.spawn('bash')
    newbash_proc.sendline('scp -r %s/tovpn/* %s:./TestBench'%(workdir,conf['vpns']['1st']['ssh']))
    wait_server(conf,newbash_proc)
    newbash_proc.sendline('scp -r %s/todp/* %s:./TestBench'%(workdir,conf['dps']['1st']['ssh']))
    wait_server(conf,newbash_proc)

    #####################<check precondition>########################
    ssh_vpn_proc.sendline("python check_node_health.py '%s'"%(conf['nodes']['1st']['name']))
    wait_server(conf,ssh_vpn_proc,'vpn')
    print(ssh_vpn_proc.before)
    if not(ssh_vpn_proc.before.find('failure') == -1):
        print('precondition failure: %s'%(ssh_vpn_proc.before))
        raise Exception('check_node_health failure')
    elif not(ssh_vpn_proc.before.find('success') == -1):
        print('node health ok.')
    else:
        print('abortion failure: %s'%(ssh_vpn_proc.before))
        raise Exception('abortion failure')
    #2nd para for check_module_health: 'config','log'
    ssh_dp_proc.sendline("python check_module_health.py '%s' \"%s\""%(conf['nodes']['1st']['name'],str(['log'])))
    wait_server(conf,ssh_dp_proc,'dp')
    if not(ssh_dp_proc.before.find('failure') == -1):
        print('precondition failure: %s'%(ssh_dp_proc.before))
        raise Exception('check_module_health failure')
    elif not(ssh_dp_proc.before.find('success') == -1):
        print('module health ok.')
    else:
        print('abortion failure: %s'%(ssh_dp_proc.before))
        raise Exception('abortion failure')

    #####################<Test procedure>########################
    ssh_vpn_proc.sendline("ssh -p 443 %s"%(conf['nodes']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc,'node')
    ssh_vpn_proc.sendline("reboot")
    time.sleep(1)
    ssh_vpn_proc.close(force=True)

    time.sleep(120)

    #####################<check postcondition>########################
    #T_reconnect to vpn
    ssh_vpn_proc = pexpect.spawn("ssh %s"%(conf['vpns']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc,'vpn')
    ssh_vpn_proc.sendline("cd TestBench")
    wait_server(conf,ssh_vpn_proc,'vpn')

    #congratulations:
    print('TestCase finished success')

    #restore
    ssh_vpn_proc.close(force=True)
    ssh_dp_proc.close(force=True)

    #T_update_config,T_random
    import random
    newvalue = random.randint(0,65535) + int(time.time())
    ssh_dp_proc.sendline("python update_config.py %s \"%s\""%\
            (conf['nodes']['1st']['name'],str({"testvalue":newvalue})))
    wait_server(conf,ssh_dp_proc,'dp')
    if not(ssh_dp_proc.before.find('failure') == -1):
        print('update config failure: %s'%(ssh_dp_proc.before))
        raise Exception('update config failure')
    elif not(ssh_dp_proc.before.find('success') == -1):
        print('update config ok.')
    else:
        print('abortion failure: %s'%(ssh_dp_proc.before))
        raise Exception('abortion failure')

    #T_check_config
    ssh_vpn_proc.sendline("python check_config.py '%s' \"%s\""%\
            (conf['nodes']['1st']['name'],str({"testvalue":newvalue})))
    wait_server(conf,ssh_vpn_proc,'vpn')
    if not(ssh_vpn_proc.before.find('failure') == -1):
        print('postcondition failure: %s'%(ssh_vpn_proc.before))
        raise Exception('check_config failure')
    elif not(ssh_vpn_proc.before.find('success') == -1):
        print('check config ok.')
    else:
        print('abortion failure: %s'%(ssh_vpn_proc.before))
        raise Exception('abortion failure')

    #T_restore_config
    ssh_dp_proc.sendline("python restore_config.py %s"%(conf['nodes']['1st']['name']))
    wait_server(conf,ssh_dp_proc,'dp')

    #T_migrate DP
    ssh_dp_proc.sendline("python restore_config.py %s"%(conf['nodes']['1st']['name']))
    wait_server(conf,ssh_dp_proc,'dp')

    ssh_dp_proc.sendline("python update_config.py %s \"%s\""%\
            (conf['nodes']['1st']['name'],str({"hostname": "https://phone:11222011@%s"%(conf['dps']['1st']['addr'])})))
    wait_server(conf,ssh_dp_proc,'dp')
    if not(ssh_dp_proc.before.find('failure') == -1):
        print('update config failure: %s'%(ssh_dp_proc.before))
        raise Exception('update config failure')
    elif not(ssh_dp_proc.before.find('success') == -1):
        print('update config ok.')
    else:
        print('abortion failure: %s'%(ssh_dp_proc.before))
        raise Exception('abortion failure')

    ssh_newdp_proc.sendline("python update_config.py %s \"%s\""%\
            (conf['nodes']['1st']['name'],str({"hostname": "https://phone:11222011@%s"%(conf['dps']['1st']['addr'])})))
    wait_server(conf,ssh_newdp_proc,'dp')
    if not(ssh_newdp_proc.before.find('failure') == -1):
        print('update config failure: %s'%(ssh_newdp_proc.before))
        raise Exception('update config failure')
    elif not(ssh_newdp_proc.before.find('success') == -1):
        print('update config ok.')
    else:
        print('abortion failure: %s'%(ssh_newdp_proc.before))
        raise Exception('abortion failure')

    #T_restart FS. login to node
    ssh_vpn_proc.sendline("ssh -p 443 %s"%(conf['nodes']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc,'node')

    #stop FusionSensor
    ssh_vpn_proc.sendline("am force-stop com.baysensors.FusionSensor")
    wait_server(conf,ssh_vpn_proc,'node')

    #start FusionSensor
    ssh_vpn_proc.sendline("am start -n com.baysensors.FusionSensor/com.baysensors.embedded.os.android.fusionsensor.FusionSensor")
    wait_server(conf,ssh_vpn_proc,'node')

    ssh_vpn_proc.sendline("exit")
    wait_server(conf,ssh_vpn_proc,'vpn')
    time.sleep(180)

    #T_kill_process
    ssh_vpn_proc.sendline("ssh -p 443 %s"%(conf['nodes']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc,'node')
    #get the PID of FusionSensor, then kill the process by PID
    ssh_vpn_proc.sendline("ps|grep com.baysensors.FusionSensor|awk '{print $2}'")
    wait_server(conf,ssh_vpn_proc,'node')
    PID = ssh_vpn_proc.before.split()[-1]
    ssh_vpn_proc.sendline("kill %s"%(PID))
    wait_server(conf,ssh_vpn_proc,'node')

    #reconnect to vpn
    ssh_vpn_proc.sendline("exit")
    wait_server(conf,ssh_vpn_proc,'vpn')

    #T_record event time
    occurTime = time.strftime('%Y-%m-%d %H:%M:%S',time.gmtime())

    #T_stopWlan0 on device for a specified duration(i.e. 5s)
    ssh_vpn_proc_stop_wlan = pexpect.spawn("ssh %s"%(conf['vpns']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc_stop_wlan,'vpn')
    ssh_vpn_proc_stop_wlan.sendline("cd TestBench")
    wait_server(conf,ssh_vpn_proc_stop_wlan,'vpn')
    ssh_vpn_proc_stop_wlan.sendline("scp -P 443 stopWlan0.sh %s:/mnt/sdcard/"%(conf['nodes']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc_stop_wlan,'vpn')
    ssh_vpn_proc_stop_wlan.sendline("ssh -p 443 %s"%(conf['nodes']['1st']['ssh']))
    wait_server(conf,ssh_vpn_proc_stop_wlan,'node')
    ssh_vpn_proc_stop_wlan.sendline("cd /mnt/sdcard/;sh stopWlan0.sh 5&")

    #T_workHours
    cur_time = time.time()
    (cur_region,opp_region) = get_time_region(cur_time)
    ssh_dp_proc.sendline("python update_config.py %s \"%s\""\
            %(conf['nodes']['1st']['name'],\
            str({"workHours": "%s"%cur_region})))
    wait_server(conf,ssh_dp_proc,'dp')
    if not(ssh_dp_proc.before.find('failure') == -1):
        print('update config failure: %s'%(ssh_dp_proc.before))
        raise Exception('update config failure')
    elif not(ssh_dp_proc.before.find('success') == -1):
        print('update config ok.')
    else:
        print('abortion failure. %s'%(ssh_dp_proc.before))
        raise Exception('abortion failure')

    #for loop
    ssh_vpn_proc.sendline("for i in `seq 100`;do cp /mnt/sdcard/eventFile\
            /mnt/sdcard/event/FS-Logger-$i;done")

    #T_check_file_exist
    ssh_dp_proc.sendline("python check_file_exist.py %s %s"%(os.path.join(conf['svr_video_dir'],conf['nodes']['1st']['name']),nameString))
    wait_server(conf,ssh_dp_proc,'dp')
    if not(ssh_dp_proc.before.find('failure') == -1):
        print('postcondition failure: %s'%(ssh_dp_proc.before))
        raise Exception('check_data_exist failure')
    elif not(ssh_dp_proc.before.find('success') == -1):
        print('check_data_exist success.')
    else:
        print('abortion failure: %s'%(ssh_dp_proc.before))
        raise Exception('abortion failure')


